package com.guyuu.system.model;

public class WikiUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_user_role.user_role_id
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String userRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_user_role.role_id
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_user_role.user_id
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_user_role.user_role_id
     *
     * @return the value of guu_wiki_user_role.user_role_id
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_user_role.user_role_id
     *
     * @param userRoleId the value for guu_wiki_user_role.user_role_id
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setUserRoleId(String userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_user_role.role_id
     *
     * @return the value of guu_wiki_user_role.role_id
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_user_role.role_id
     *
     * @param roleId the value for guu_wiki_user_role.role_id
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_user_role.user_id
     *
     * @return the value of guu_wiki_user_role.user_id
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_user_role.user_id
     *
     * @param userId the value for guu_wiki_user_role.user_id
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}