package com.guyuu.system.model;

public class WikiUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_user.user_id
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_user.register_name
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String registerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_user.email
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_user.password
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_user.phone
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_user.user_name
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_user.birthday
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_user.user_sex
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_user.person_sign
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String personSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_user.birth_place
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String birthPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_user.live_place
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String livePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_user.person_introduction
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String personIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_user.remark
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_user.user_id
     *
     * @return the value of guu_wiki_user.user_id
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_user.user_id
     *
     * @param userId the value for guu_wiki_user.user_id
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_user.register_name
     *
     * @return the value of guu_wiki_user.register_name
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getRegisterName() {
        return registerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_user.register_name
     *
     * @param registerName the value for guu_wiki_user.register_name
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setRegisterName(String registerName) {
        this.registerName = registerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_user.email
     *
     * @return the value of guu_wiki_user.email
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_user.email
     *
     * @param email the value for guu_wiki_user.email
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_user.password
     *
     * @return the value of guu_wiki_user.password
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_user.password
     *
     * @param password the value for guu_wiki_user.password
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_user.phone
     *
     * @return the value of guu_wiki_user.phone
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_user.phone
     *
     * @param phone the value for guu_wiki_user.phone
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_user.user_name
     *
     * @return the value of guu_wiki_user.user_name
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_user.user_name
     *
     * @param userName the value for guu_wiki_user.user_name
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_user.birthday
     *
     * @return the value of guu_wiki_user.birthday
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_user.birthday
     *
     * @param birthday the value for guu_wiki_user.birthday
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_user.user_sex
     *
     * @return the value of guu_wiki_user.user_sex
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_user.user_sex
     *
     * @param userSex the value for guu_wiki_user.user_sex
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_user.person_sign
     *
     * @return the value of guu_wiki_user.person_sign
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getPersonSign() {
        return personSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_user.person_sign
     *
     * @param personSign the value for guu_wiki_user.person_sign
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setPersonSign(String personSign) {
        this.personSign = personSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_user.birth_place
     *
     * @return the value of guu_wiki_user.birth_place
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getBirthPlace() {
        return birthPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_user.birth_place
     *
     * @param birthPlace the value for guu_wiki_user.birth_place
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_user.live_place
     *
     * @return the value of guu_wiki_user.live_place
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getLivePlace() {
        return livePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_user.live_place
     *
     * @param livePlace the value for guu_wiki_user.live_place
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setLivePlace(String livePlace) {
        this.livePlace = livePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_user.person_introduction
     *
     * @return the value of guu_wiki_user.person_introduction
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getPersonIntroduction() {
        return personIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_user.person_introduction
     *
     * @param personIntroduction the value for guu_wiki_user.person_introduction
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setPersonIntroduction(String personIntroduction) {
        this.personIntroduction = personIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_user.remark
     *
     * @return the value of guu_wiki_user.remark
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_user.remark
     *
     * @param remark the value for guu_wiki_user.remark
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}