package com.guyuu.system.model;

import java.util.Date;

public class WikiRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_role.role_code
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_role.role_name
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_role.create_user_id
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_role.create_user_name
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_role.create_time
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_role.remark
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_role.role_code
     *
     * @return the value of guu_wiki_role.role_code
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_role.role_code
     *
     * @param roleCode the value for guu_wiki_role.role_code
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_role.role_name
     *
     * @return the value of guu_wiki_role.role_name
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_role.role_name
     *
     * @param roleName the value for guu_wiki_role.role_name
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_role.create_user_id
     *
     * @return the value of guu_wiki_role.create_user_id
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_role.create_user_id
     *
     * @param createUserId the value for guu_wiki_role.create_user_id
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_role.create_user_name
     *
     * @return the value of guu_wiki_role.create_user_name
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_role.create_user_name
     *
     * @param createUserName the value for guu_wiki_role.create_user_name
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_role.create_time
     *
     * @return the value of guu_wiki_role.create_time
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_role.create_time
     *
     * @param createTime the value for guu_wiki_role.create_time
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_role.remark
     *
     * @return the value of guu_wiki_role.remark
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_role.remark
     *
     * @param remark the value for guu_wiki_role.remark
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}