package com.guyuu.baike.mappers;

import com.guyuu.baike.model.WikiEntryHistory;
import com.guyuu.baike.model.WikiEntryHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WikiEntryHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_history
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int countByExample(WikiEntryHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_history
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int deleteByExample(WikiEntryHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_history
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int deleteByPrimaryKey(String historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_history
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int insert(WikiEntryHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_history
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int insertSelective(WikiEntryHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_history
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    List<WikiEntryHistory> selectByExample(WikiEntryHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_history
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    WikiEntryHistory selectByPrimaryKey(String historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_history
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int updateByExampleSelective(@Param("record") WikiEntryHistory record, @Param("example") WikiEntryHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_history
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int updateByExample(@Param("record") WikiEntryHistory record, @Param("example") WikiEntryHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_history
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int updateByPrimaryKeySelective(WikiEntryHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_history
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int updateByPrimaryKey(WikiEntryHistory record);
}