package com.guyuu.baike.mappers;

import com.guyuu.baike.model.WikiEntry;
import com.guyuu.baike.model.WikiEntryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WikiEntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int countByExample(WikiEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int deleteByExample(WikiEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int deleteByPrimaryKey(String entryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int insert(WikiEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int insertSelective(WikiEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    List<WikiEntry> selectByExample(WikiEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    WikiEntry selectByPrimaryKey(String entryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int updateByExampleSelective(@Param("record") WikiEntry record, @Param("example") WikiEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int updateByExample(@Param("record") WikiEntry record, @Param("example") WikiEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int updateByPrimaryKeySelective(WikiEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int updateByPrimaryKey(WikiEntry record);
}