package com.guyuu.baike.mappers;

import com.guyuu.baike.model.WikiEntryType;
import com.guyuu.baike.model.WikiEntryTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WikiEntryTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_type
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int countByExample(WikiEntryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_type
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int deleteByExample(WikiEntryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_type
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int insert(WikiEntryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_type
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int insertSelective(WikiEntryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_type
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    List<WikiEntryType> selectByExample(WikiEntryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_type
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int updateByExampleSelective(@Param("record") WikiEntryType record, @Param("example") WikiEntryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_type
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int updateByExample(@Param("record") WikiEntryType record, @Param("example") WikiEntryTypeExample example);
}