package com.guyuu.baike.mappers;

import com.guyuu.baike.model.WikiEntryList;
import com.guyuu.baike.model.WikiEntryListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WikiEntryListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_list
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int countByExample(WikiEntryListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_list
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int deleteByExample(WikiEntryListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_list
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int deleteByPrimaryKey(String catalogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_list
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int insert(WikiEntryList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_list
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int insertSelective(WikiEntryList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_list
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    List<WikiEntryList> selectByExampleWithBLOBs(WikiEntryListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_list
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    List<WikiEntryList> selectByExample(WikiEntryListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_list
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    WikiEntryList selectByPrimaryKey(String catalogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_list
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int updateByExampleSelective(@Param("record") WikiEntryList record, @Param("example") WikiEntryListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_list
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") WikiEntryList record, @Param("example") WikiEntryListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_list
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int updateByExample(@Param("record") WikiEntryList record, @Param("example") WikiEntryListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_list
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int updateByPrimaryKeySelective(WikiEntryList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_list
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(WikiEntryList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry_list
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    int updateByPrimaryKey(WikiEntryList record);
}