package com.guyuu.system.mappers;

import com.guyuu.system.model.WikiRole;
import com.guyuu.system.model.WikiRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WikiRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    int countByExample(WikiRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    int deleteByExample(WikiRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    int deleteByPrimaryKey(String roleCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    int insert(WikiRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    int insertSelective(WikiRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    List<WikiRole> selectByExample(WikiRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    WikiRole selectByPrimaryKey(String roleCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    int updateByExampleSelective(@Param("record") WikiRole record, @Param("example") WikiRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    int updateByExample(@Param("record") WikiRole record, @Param("example") WikiRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    int updateByPrimaryKeySelective(WikiRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    int updateByPrimaryKey(WikiRole record);
}