package com.guyuu.system.mappers;

import com.guyuu.system.model.WikiUserRole;
import com.guyuu.system.model.WikiUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WikiUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_user_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    int countByExample(WikiUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_user_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    int deleteByExample(WikiUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_user_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    int deleteByPrimaryKey(String userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_user_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    int insert(WikiUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_user_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    int insertSelective(WikiUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_user_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    List<WikiUserRole> selectByExample(WikiUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_user_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    WikiUserRole selectByPrimaryKey(String userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_user_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    int updateByExampleSelective(@Param("record") WikiUserRole record, @Param("example") WikiUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_user_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    int updateByExample(@Param("record") WikiUserRole record, @Param("example") WikiUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_user_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    int updateByPrimaryKeySelective(WikiUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_user_role
     *
     * @mbggenerated Mon Jun 09 01:51:49 CST 2014
     */
    int updateByPrimaryKey(WikiUserRole record);
}