package com.guyuu.baike.model;

import java.util.Date;

public class WikiCatalogHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_catalog_history.history_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String historyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_catalog_history.catalog_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String catalogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_catalog_history.catalog_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String catalogName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_catalog_history.entry_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String entryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_catalog_history.entry_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String entryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_catalog_history.entry_version
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String entryVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_catalog_history.catalog_status
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String catalogStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_catalog_history.catalog_sort
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private Integer catalogSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_catalog_history.catalog_sign
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String catalogSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_catalog_history.create_user_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_catalog_history.update_user_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_catalog_history.create_user_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_catalog_history.update_user_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String updateUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_catalog_history.create_time
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_catalog_history.update_time
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_catalog_history.remark
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_catalog_history.catalog_content
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String catalogContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_catalog_history.history_id
     *
     * @return the value of guu_wiki_entry_catalog_history.history_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getHistoryId() {
        return historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_catalog_history.history_id
     *
     * @param historyId the value for guu_wiki_entry_catalog_history.history_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setHistoryId(String historyId) {
        this.historyId = historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_catalog_history.catalog_id
     *
     * @return the value of guu_wiki_entry_catalog_history.catalog_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_catalog_history.catalog_id
     *
     * @param catalogId the value for guu_wiki_entry_catalog_history.catalog_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setCatalogId(String catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_catalog_history.catalog_name
     *
     * @return the value of guu_wiki_entry_catalog_history.catalog_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getCatalogName() {
        return catalogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_catalog_history.catalog_name
     *
     * @param catalogName the value for guu_wiki_entry_catalog_history.catalog_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_catalog_history.entry_id
     *
     * @return the value of guu_wiki_entry_catalog_history.entry_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getEntryId() {
        return entryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_catalog_history.entry_id
     *
     * @param entryId the value for guu_wiki_entry_catalog_history.entry_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setEntryId(String entryId) {
        this.entryId = entryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_catalog_history.entry_name
     *
     * @return the value of guu_wiki_entry_catalog_history.entry_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getEntryName() {
        return entryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_catalog_history.entry_name
     *
     * @param entryName the value for guu_wiki_entry_catalog_history.entry_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setEntryName(String entryName) {
        this.entryName = entryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_catalog_history.entry_version
     *
     * @return the value of guu_wiki_entry_catalog_history.entry_version
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getEntryVersion() {
        return entryVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_catalog_history.entry_version
     *
     * @param entryVersion the value for guu_wiki_entry_catalog_history.entry_version
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setEntryVersion(String entryVersion) {
        this.entryVersion = entryVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_catalog_history.catalog_status
     *
     * @return the value of guu_wiki_entry_catalog_history.catalog_status
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getCatalogStatus() {
        return catalogStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_catalog_history.catalog_status
     *
     * @param catalogStatus the value for guu_wiki_entry_catalog_history.catalog_status
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setCatalogStatus(String catalogStatus) {
        this.catalogStatus = catalogStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_catalog_history.catalog_sort
     *
     * @return the value of guu_wiki_entry_catalog_history.catalog_sort
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public Integer getCatalogSort() {
        return catalogSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_catalog_history.catalog_sort
     *
     * @param catalogSort the value for guu_wiki_entry_catalog_history.catalog_sort
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setCatalogSort(Integer catalogSort) {
        this.catalogSort = catalogSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_catalog_history.catalog_sign
     *
     * @return the value of guu_wiki_entry_catalog_history.catalog_sign
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getCatalogSign() {
        return catalogSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_catalog_history.catalog_sign
     *
     * @param catalogSign the value for guu_wiki_entry_catalog_history.catalog_sign
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setCatalogSign(String catalogSign) {
        this.catalogSign = catalogSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_catalog_history.create_user_id
     *
     * @return the value of guu_wiki_entry_catalog_history.create_user_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_catalog_history.create_user_id
     *
     * @param createUserId the value for guu_wiki_entry_catalog_history.create_user_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_catalog_history.update_user_id
     *
     * @return the value of guu_wiki_entry_catalog_history.update_user_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_catalog_history.update_user_id
     *
     * @param updateUserId the value for guu_wiki_entry_catalog_history.update_user_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_catalog_history.create_user_name
     *
     * @return the value of guu_wiki_entry_catalog_history.create_user_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_catalog_history.create_user_name
     *
     * @param createUserName the value for guu_wiki_entry_catalog_history.create_user_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_catalog_history.update_user_name
     *
     * @return the value of guu_wiki_entry_catalog_history.update_user_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getUpdateUserName() {
        return updateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_catalog_history.update_user_name
     *
     * @param updateUserName the value for guu_wiki_entry_catalog_history.update_user_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setUpdateUserName(String updateUserName) {
        this.updateUserName = updateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_catalog_history.create_time
     *
     * @return the value of guu_wiki_entry_catalog_history.create_time
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_catalog_history.create_time
     *
     * @param createTime the value for guu_wiki_entry_catalog_history.create_time
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_catalog_history.update_time
     *
     * @return the value of guu_wiki_entry_catalog_history.update_time
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_catalog_history.update_time
     *
     * @param updateTime the value for guu_wiki_entry_catalog_history.update_time
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_catalog_history.remark
     *
     * @return the value of guu_wiki_entry_catalog_history.remark
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_catalog_history.remark
     *
     * @param remark the value for guu_wiki_entry_catalog_history.remark
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_catalog_history.catalog_content
     *
     * @return the value of guu_wiki_entry_catalog_history.catalog_content
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getCatalogContent() {
        return catalogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_catalog_history.catalog_content
     *
     * @param catalogContent the value for guu_wiki_entry_catalog_history.catalog_content
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setCatalogContent(String catalogContent) {
        this.catalogContent = catalogContent;
    }
}