package com.guyuu.baike.model;

import java.util.Date;

public class WikiEntryType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_type.type_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_type.parent_type_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String parentTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_type.type_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_type.create_time
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_type.create_user_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_type.create_user_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_type.remark
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_type.type_id
     *
     * @return the value of guu_wiki_entry_type.type_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_type.type_id
     *
     * @param typeId the value for guu_wiki_entry_type.type_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_type.parent_type_id
     *
     * @return the value of guu_wiki_entry_type.parent_type_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getParentTypeId() {
        return parentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_type.parent_type_id
     *
     * @param parentTypeId the value for guu_wiki_entry_type.parent_type_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setParentTypeId(String parentTypeId) {
        this.parentTypeId = parentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_type.type_name
     *
     * @return the value of guu_wiki_entry_type.type_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_type.type_name
     *
     * @param typeName the value for guu_wiki_entry_type.type_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_type.create_time
     *
     * @return the value of guu_wiki_entry_type.create_time
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_type.create_time
     *
     * @param createTime the value for guu_wiki_entry_type.create_time
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_type.create_user_name
     *
     * @return the value of guu_wiki_entry_type.create_user_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_type.create_user_name
     *
     * @param createUserName the value for guu_wiki_entry_type.create_user_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_type.create_user_id
     *
     * @return the value of guu_wiki_entry_type.create_user_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_type.create_user_id
     *
     * @param createUserId the value for guu_wiki_entry_type.create_user_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_type.remark
     *
     * @return the value of guu_wiki_entry_type.remark
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_type.remark
     *
     * @param remark the value for guu_wiki_entry_type.remark
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}