package com.guyuu.baike.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WikiEntryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public WikiEntryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEntryIdIsNull() {
            addCriterion("entry_id is null");
            return (Criteria) this;
        }

        public Criteria andEntryIdIsNotNull() {
            addCriterion("entry_id is not null");
            return (Criteria) this;
        }

        public Criteria andEntryIdEqualTo(String value) {
            addCriterion("entry_id =", value, "entryId");
            return (Criteria) this;
        }

        public Criteria andEntryIdNotEqualTo(String value) {
            addCriterion("entry_id <>", value, "entryId");
            return (Criteria) this;
        }

        public Criteria andEntryIdGreaterThan(String value) {
            addCriterion("entry_id >", value, "entryId");
            return (Criteria) this;
        }

        public Criteria andEntryIdGreaterThanOrEqualTo(String value) {
            addCriterion("entry_id >=", value, "entryId");
            return (Criteria) this;
        }

        public Criteria andEntryIdLessThan(String value) {
            addCriterion("entry_id <", value, "entryId");
            return (Criteria) this;
        }

        public Criteria andEntryIdLessThanOrEqualTo(String value) {
            addCriterion("entry_id <=", value, "entryId");
            return (Criteria) this;
        }

        public Criteria andEntryIdLike(String value) {
            addCriterion("entry_id like", value, "entryId");
            return (Criteria) this;
        }

        public Criteria andEntryIdNotLike(String value) {
            addCriterion("entry_id not like", value, "entryId");
            return (Criteria) this;
        }

        public Criteria andEntryIdIn(List<String> values) {
            addCriterion("entry_id in", values, "entryId");
            return (Criteria) this;
        }

        public Criteria andEntryIdNotIn(List<String> values) {
            addCriterion("entry_id not in", values, "entryId");
            return (Criteria) this;
        }

        public Criteria andEntryIdBetween(String value1, String value2) {
            addCriterion("entry_id between", value1, value2, "entryId");
            return (Criteria) this;
        }

        public Criteria andEntryIdNotBetween(String value1, String value2) {
            addCriterion("entry_id not between", value1, value2, "entryId");
            return (Criteria) this;
        }

        public Criteria andEntryVersionIsNull() {
            addCriterion("entry_version is null");
            return (Criteria) this;
        }

        public Criteria andEntryVersionIsNotNull() {
            addCriterion("entry_version is not null");
            return (Criteria) this;
        }

        public Criteria andEntryVersionEqualTo(String value) {
            addCriterion("entry_version =", value, "entryVersion");
            return (Criteria) this;
        }

        public Criteria andEntryVersionNotEqualTo(String value) {
            addCriterion("entry_version <>", value, "entryVersion");
            return (Criteria) this;
        }

        public Criteria andEntryVersionGreaterThan(String value) {
            addCriterion("entry_version >", value, "entryVersion");
            return (Criteria) this;
        }

        public Criteria andEntryVersionGreaterThanOrEqualTo(String value) {
            addCriterion("entry_version >=", value, "entryVersion");
            return (Criteria) this;
        }

        public Criteria andEntryVersionLessThan(String value) {
            addCriterion("entry_version <", value, "entryVersion");
            return (Criteria) this;
        }

        public Criteria andEntryVersionLessThanOrEqualTo(String value) {
            addCriterion("entry_version <=", value, "entryVersion");
            return (Criteria) this;
        }

        public Criteria andEntryVersionLike(String value) {
            addCriterion("entry_version like", value, "entryVersion");
            return (Criteria) this;
        }

        public Criteria andEntryVersionNotLike(String value) {
            addCriterion("entry_version not like", value, "entryVersion");
            return (Criteria) this;
        }

        public Criteria andEntryVersionIn(List<String> values) {
            addCriterion("entry_version in", values, "entryVersion");
            return (Criteria) this;
        }

        public Criteria andEntryVersionNotIn(List<String> values) {
            addCriterion("entry_version not in", values, "entryVersion");
            return (Criteria) this;
        }

        public Criteria andEntryVersionBetween(String value1, String value2) {
            addCriterion("entry_version between", value1, value2, "entryVersion");
            return (Criteria) this;
        }

        public Criteria andEntryVersionNotBetween(String value1, String value2) {
            addCriterion("entry_version not between", value1, value2, "entryVersion");
            return (Criteria) this;
        }

        public Criteria andEntryNameIsNull() {
            addCriterion("entry_name is null");
            return (Criteria) this;
        }

        public Criteria andEntryNameIsNotNull() {
            addCriterion("entry_name is not null");
            return (Criteria) this;
        }

        public Criteria andEntryNameEqualTo(String value) {
            addCriterion("entry_name =", value, "entryName");
            return (Criteria) this;
        }

        public Criteria andEntryNameNotEqualTo(String value) {
            addCriterion("entry_name <>", value, "entryName");
            return (Criteria) this;
        }

        public Criteria andEntryNameGreaterThan(String value) {
            addCriterion("entry_name >", value, "entryName");
            return (Criteria) this;
        }

        public Criteria andEntryNameGreaterThanOrEqualTo(String value) {
            addCriterion("entry_name >=", value, "entryName");
            return (Criteria) this;
        }

        public Criteria andEntryNameLessThan(String value) {
            addCriterion("entry_name <", value, "entryName");
            return (Criteria) this;
        }

        public Criteria andEntryNameLessThanOrEqualTo(String value) {
            addCriterion("entry_name <=", value, "entryName");
            return (Criteria) this;
        }

        public Criteria andEntryNameLike(String value) {
            addCriterion("entry_name like", value, "entryName");
            return (Criteria) this;
        }

        public Criteria andEntryNameNotLike(String value) {
            addCriterion("entry_name not like", value, "entryName");
            return (Criteria) this;
        }

        public Criteria andEntryNameIn(List<String> values) {
            addCriterion("entry_name in", values, "entryName");
            return (Criteria) this;
        }

        public Criteria andEntryNameNotIn(List<String> values) {
            addCriterion("entry_name not in", values, "entryName");
            return (Criteria) this;
        }

        public Criteria andEntryNameBetween(String value1, String value2) {
            addCriterion("entry_name between", value1, value2, "entryName");
            return (Criteria) this;
        }

        public Criteria andEntryNameNotBetween(String value1, String value2) {
            addCriterion("entry_name not between", value1, value2, "entryName");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameIsNull() {
            addCriterion("create_user_name is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameIsNotNull() {
            addCriterion("create_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameEqualTo(String value) {
            addCriterion("create_user_name =", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotEqualTo(String value) {
            addCriterion("create_user_name <>", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameGreaterThan(String value) {
            addCriterion("create_user_name >", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_name >=", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameLessThan(String value) {
            addCriterion("create_user_name <", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameLessThanOrEqualTo(String value) {
            addCriterion("create_user_name <=", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameLike(String value) {
            addCriterion("create_user_name like", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotLike(String value) {
            addCriterion("create_user_name not like", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameIn(List<String> values) {
            addCriterion("create_user_name in", values, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotIn(List<String> values) {
            addCriterion("create_user_name not in", values, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameBetween(String value1, String value2) {
            addCriterion("create_user_name between", value1, value2, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotBetween(String value1, String value2) {
            addCriterion("create_user_name not between", value1, value2, "createUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameIsNull() {
            addCriterion("update_user_name is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameIsNotNull() {
            addCriterion("update_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameEqualTo(String value) {
            addCriterion("update_user_name =", value, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameNotEqualTo(String value) {
            addCriterion("update_user_name <>", value, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameGreaterThan(String value) {
            addCriterion("update_user_name >", value, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_name >=", value, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameLessThan(String value) {
            addCriterion("update_user_name <", value, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameLessThanOrEqualTo(String value) {
            addCriterion("update_user_name <=", value, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameLike(String value) {
            addCriterion("update_user_name like", value, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameNotLike(String value) {
            addCriterion("update_user_name not like", value, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameIn(List<String> values) {
            addCriterion("update_user_name in", values, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameNotIn(List<String> values) {
            addCriterion("update_user_name not in", values, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameBetween(String value1, String value2) {
            addCriterion("update_user_name between", value1, value2, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNameNotBetween(String value1, String value2) {
            addCriterion("update_user_name not between", value1, value2, "updateUserName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andBrowseAmountIsNull() {
            addCriterion("browse_amount is null");
            return (Criteria) this;
        }

        public Criteria andBrowseAmountIsNotNull() {
            addCriterion("browse_amount is not null");
            return (Criteria) this;
        }

        public Criteria andBrowseAmountEqualTo(Integer value) {
            addCriterion("browse_amount =", value, "browseAmount");
            return (Criteria) this;
        }

        public Criteria andBrowseAmountNotEqualTo(Integer value) {
            addCriterion("browse_amount <>", value, "browseAmount");
            return (Criteria) this;
        }

        public Criteria andBrowseAmountGreaterThan(Integer value) {
            addCriterion("browse_amount >", value, "browseAmount");
            return (Criteria) this;
        }

        public Criteria andBrowseAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("browse_amount >=", value, "browseAmount");
            return (Criteria) this;
        }

        public Criteria andBrowseAmountLessThan(Integer value) {
            addCriterion("browse_amount <", value, "browseAmount");
            return (Criteria) this;
        }

        public Criteria andBrowseAmountLessThanOrEqualTo(Integer value) {
            addCriterion("browse_amount <=", value, "browseAmount");
            return (Criteria) this;
        }

        public Criteria andBrowseAmountIn(List<Integer> values) {
            addCriterion("browse_amount in", values, "browseAmount");
            return (Criteria) this;
        }

        public Criteria andBrowseAmountNotIn(List<Integer> values) {
            addCriterion("browse_amount not in", values, "browseAmount");
            return (Criteria) this;
        }

        public Criteria andBrowseAmountBetween(Integer value1, Integer value2) {
            addCriterion("browse_amount between", value1, value2, "browseAmount");
            return (Criteria) this;
        }

        public Criteria andBrowseAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("browse_amount not between", value1, value2, "browseAmount");
            return (Criteria) this;
        }

        public Criteria andEntryEditAmountIsNull() {
            addCriterion("entry_edit_amount is null");
            return (Criteria) this;
        }

        public Criteria andEntryEditAmountIsNotNull() {
            addCriterion("entry_edit_amount is not null");
            return (Criteria) this;
        }

        public Criteria andEntryEditAmountEqualTo(Integer value) {
            addCriterion("entry_edit_amount =", value, "entryEditAmount");
            return (Criteria) this;
        }

        public Criteria andEntryEditAmountNotEqualTo(Integer value) {
            addCriterion("entry_edit_amount <>", value, "entryEditAmount");
            return (Criteria) this;
        }

        public Criteria andEntryEditAmountGreaterThan(Integer value) {
            addCriterion("entry_edit_amount >", value, "entryEditAmount");
            return (Criteria) this;
        }

        public Criteria andEntryEditAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("entry_edit_amount >=", value, "entryEditAmount");
            return (Criteria) this;
        }

        public Criteria andEntryEditAmountLessThan(Integer value) {
            addCriterion("entry_edit_amount <", value, "entryEditAmount");
            return (Criteria) this;
        }

        public Criteria andEntryEditAmountLessThanOrEqualTo(Integer value) {
            addCriterion("entry_edit_amount <=", value, "entryEditAmount");
            return (Criteria) this;
        }

        public Criteria andEntryEditAmountIn(List<Integer> values) {
            addCriterion("entry_edit_amount in", values, "entryEditAmount");
            return (Criteria) this;
        }

        public Criteria andEntryEditAmountNotIn(List<Integer> values) {
            addCriterion("entry_edit_amount not in", values, "entryEditAmount");
            return (Criteria) this;
        }

        public Criteria andEntryEditAmountBetween(Integer value1, Integer value2) {
            addCriterion("entry_edit_amount between", value1, value2, "entryEditAmount");
            return (Criteria) this;
        }

        public Criteria andEntryEditAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("entry_edit_amount not between", value1, value2, "entryEditAmount");
            return (Criteria) this;
        }

        public Criteria andModifyReasonIsNull() {
            addCriterion("modify_reason is null");
            return (Criteria) this;
        }

        public Criteria andModifyReasonIsNotNull() {
            addCriterion("modify_reason is not null");
            return (Criteria) this;
        }

        public Criteria andModifyReasonEqualTo(String value) {
            addCriterion("modify_reason =", value, "modifyReason");
            return (Criteria) this;
        }

        public Criteria andModifyReasonNotEqualTo(String value) {
            addCriterion("modify_reason <>", value, "modifyReason");
            return (Criteria) this;
        }

        public Criteria andModifyReasonGreaterThan(String value) {
            addCriterion("modify_reason >", value, "modifyReason");
            return (Criteria) this;
        }

        public Criteria andModifyReasonGreaterThanOrEqualTo(String value) {
            addCriterion("modify_reason >=", value, "modifyReason");
            return (Criteria) this;
        }

        public Criteria andModifyReasonLessThan(String value) {
            addCriterion("modify_reason <", value, "modifyReason");
            return (Criteria) this;
        }

        public Criteria andModifyReasonLessThanOrEqualTo(String value) {
            addCriterion("modify_reason <=", value, "modifyReason");
            return (Criteria) this;
        }

        public Criteria andModifyReasonLike(String value) {
            addCriterion("modify_reason like", value, "modifyReason");
            return (Criteria) this;
        }

        public Criteria andModifyReasonNotLike(String value) {
            addCriterion("modify_reason not like", value, "modifyReason");
            return (Criteria) this;
        }

        public Criteria andModifyReasonIn(List<String> values) {
            addCriterion("modify_reason in", values, "modifyReason");
            return (Criteria) this;
        }

        public Criteria andModifyReasonNotIn(List<String> values) {
            addCriterion("modify_reason not in", values, "modifyReason");
            return (Criteria) this;
        }

        public Criteria andModifyReasonBetween(String value1, String value2) {
            addCriterion("modify_reason between", value1, value2, "modifyReason");
            return (Criteria) this;
        }

        public Criteria andModifyReasonNotBetween(String value1, String value2) {
            addCriterion("modify_reason not between", value1, value2, "modifyReason");
            return (Criteria) this;
        }

        public Criteria andEntryStatusIsNull() {
            addCriterion("entry_status is null");
            return (Criteria) this;
        }

        public Criteria andEntryStatusIsNotNull() {
            addCriterion("entry_status is not null");
            return (Criteria) this;
        }

        public Criteria andEntryStatusEqualTo(String value) {
            addCriterion("entry_status =", value, "entryStatus");
            return (Criteria) this;
        }

        public Criteria andEntryStatusNotEqualTo(String value) {
            addCriterion("entry_status <>", value, "entryStatus");
            return (Criteria) this;
        }

        public Criteria andEntryStatusGreaterThan(String value) {
            addCriterion("entry_status >", value, "entryStatus");
            return (Criteria) this;
        }

        public Criteria andEntryStatusGreaterThanOrEqualTo(String value) {
            addCriterion("entry_status >=", value, "entryStatus");
            return (Criteria) this;
        }

        public Criteria andEntryStatusLessThan(String value) {
            addCriterion("entry_status <", value, "entryStatus");
            return (Criteria) this;
        }

        public Criteria andEntryStatusLessThanOrEqualTo(String value) {
            addCriterion("entry_status <=", value, "entryStatus");
            return (Criteria) this;
        }

        public Criteria andEntryStatusLike(String value) {
            addCriterion("entry_status like", value, "entryStatus");
            return (Criteria) this;
        }

        public Criteria andEntryStatusNotLike(String value) {
            addCriterion("entry_status not like", value, "entryStatus");
            return (Criteria) this;
        }

        public Criteria andEntryStatusIn(List<String> values) {
            addCriterion("entry_status in", values, "entryStatus");
            return (Criteria) this;
        }

        public Criteria andEntryStatusNotIn(List<String> values) {
            addCriterion("entry_status not in", values, "entryStatus");
            return (Criteria) this;
        }

        public Criteria andEntryStatusBetween(String value1, String value2) {
            addCriterion("entry_status between", value1, value2, "entryStatus");
            return (Criteria) this;
        }

        public Criteria andEntryStatusNotBetween(String value1, String value2) {
            addCriterion("entry_status not between", value1, value2, "entryStatus");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNull() {
            addCriterion("type_id is null");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNotNull() {
            addCriterion("type_id is not null");
            return (Criteria) this;
        }

        public Criteria andTypeIdEqualTo(String value) {
            addCriterion("type_id =", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotEqualTo(String value) {
            addCriterion("type_id <>", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThan(String value) {
            addCriterion("type_id >", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("type_id >=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThan(String value) {
            addCriterion("type_id <", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThanOrEqualTo(String value) {
            addCriterion("type_id <=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLike(String value) {
            addCriterion("type_id like", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotLike(String value) {
            addCriterion("type_id not like", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdIn(List<String> values) {
            addCriterion("type_id in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotIn(List<String> values) {
            addCriterion("type_id not in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdBetween(String value1, String value2) {
            addCriterion("type_id between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotBetween(String value1, String value2) {
            addCriterion("type_id not between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNull() {
            addCriterion("type_name is null");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNotNull() {
            addCriterion("type_name is not null");
            return (Criteria) this;
        }

        public Criteria andTypeNameEqualTo(String value) {
            addCriterion("type_name =", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotEqualTo(String value) {
            addCriterion("type_name <>", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThan(String value) {
            addCriterion("type_name >", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("type_name >=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThan(String value) {
            addCriterion("type_name <", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThanOrEqualTo(String value) {
            addCriterion("type_name <=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLike(String value) {
            addCriterion("type_name like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotLike(String value) {
            addCriterion("type_name not like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameIn(List<String> values) {
            addCriterion("type_name in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotIn(List<String> values) {
            addCriterion("type_name not in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameBetween(String value1, String value2) {
            addCriterion("type_name between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotBetween(String value1, String value2) {
            addCriterion("type_name not between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 09 01:27:10 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guu_wiki_entry
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}