package com.guyuu.baike.model;

import java.util.Date;

public class WikiEntryHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_history.history_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String historyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_history.entry_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String entryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_history.entry_version
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String entryVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_history.entry_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String entryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_history.update_user_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_history.update_user_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String updateUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_history.update_time
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_history.update_reason
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String updateReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_history.type_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_history.type_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry_history.remark
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_history.history_id
     *
     * @return the value of guu_wiki_entry_history.history_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getHistoryId() {
        return historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_history.history_id
     *
     * @param historyId the value for guu_wiki_entry_history.history_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setHistoryId(String historyId) {
        this.historyId = historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_history.entry_id
     *
     * @return the value of guu_wiki_entry_history.entry_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getEntryId() {
        return entryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_history.entry_id
     *
     * @param entryId the value for guu_wiki_entry_history.entry_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setEntryId(String entryId) {
        this.entryId = entryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_history.entry_version
     *
     * @return the value of guu_wiki_entry_history.entry_version
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getEntryVersion() {
        return entryVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_history.entry_version
     *
     * @param entryVersion the value for guu_wiki_entry_history.entry_version
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setEntryVersion(String entryVersion) {
        this.entryVersion = entryVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_history.entry_name
     *
     * @return the value of guu_wiki_entry_history.entry_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getEntryName() {
        return entryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_history.entry_name
     *
     * @param entryName the value for guu_wiki_entry_history.entry_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setEntryName(String entryName) {
        this.entryName = entryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_history.update_user_id
     *
     * @return the value of guu_wiki_entry_history.update_user_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_history.update_user_id
     *
     * @param updateUserId the value for guu_wiki_entry_history.update_user_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_history.update_user_name
     *
     * @return the value of guu_wiki_entry_history.update_user_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getUpdateUserName() {
        return updateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_history.update_user_name
     *
     * @param updateUserName the value for guu_wiki_entry_history.update_user_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setUpdateUserName(String updateUserName) {
        this.updateUserName = updateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_history.update_time
     *
     * @return the value of guu_wiki_entry_history.update_time
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_history.update_time
     *
     * @param updateTime the value for guu_wiki_entry_history.update_time
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_history.update_reason
     *
     * @return the value of guu_wiki_entry_history.update_reason
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getUpdateReason() {
        return updateReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_history.update_reason
     *
     * @param updateReason the value for guu_wiki_entry_history.update_reason
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setUpdateReason(String updateReason) {
        this.updateReason = updateReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_history.type_id
     *
     * @return the value of guu_wiki_entry_history.type_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_history.type_id
     *
     * @param typeId the value for guu_wiki_entry_history.type_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_history.type_name
     *
     * @return the value of guu_wiki_entry_history.type_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_history.type_name
     *
     * @param typeName the value for guu_wiki_entry_history.type_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry_history.remark
     *
     * @return the value of guu_wiki_entry_history.remark
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry_history.remark
     *
     * @param remark the value for guu_wiki_entry_history.remark
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}