package com.guyuu.baike.model;

import java.util.Date;

public class WikiEntry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry.entry_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String entryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry.entry_version
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String entryVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry.entry_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String entryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry.create_user_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry.update_user_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry.create_user_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry.update_user_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String updateUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry.create_time
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry.update_time
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry.browse_amount
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private Integer browseAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry.entry_edit_amount
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private Integer entryEditAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry.modify_reason
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String modifyReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry.entry_status
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String entryStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry.type_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry.type_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_wiki_entry.remark
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry.entry_id
     *
     * @return the value of guu_wiki_entry.entry_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getEntryId() {
        return entryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry.entry_id
     *
     * @param entryId the value for guu_wiki_entry.entry_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setEntryId(String entryId) {
        this.entryId = entryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry.entry_version
     *
     * @return the value of guu_wiki_entry.entry_version
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getEntryVersion() {
        return entryVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry.entry_version
     *
     * @param entryVersion the value for guu_wiki_entry.entry_version
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setEntryVersion(String entryVersion) {
        this.entryVersion = entryVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry.entry_name
     *
     * @return the value of guu_wiki_entry.entry_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getEntryName() {
        return entryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry.entry_name
     *
     * @param entryName the value for guu_wiki_entry.entry_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setEntryName(String entryName) {
        this.entryName = entryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry.create_user_id
     *
     * @return the value of guu_wiki_entry.create_user_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry.create_user_id
     *
     * @param createUserId the value for guu_wiki_entry.create_user_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry.update_user_id
     *
     * @return the value of guu_wiki_entry.update_user_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry.update_user_id
     *
     * @param updateUserId the value for guu_wiki_entry.update_user_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry.create_user_name
     *
     * @return the value of guu_wiki_entry.create_user_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry.create_user_name
     *
     * @param createUserName the value for guu_wiki_entry.create_user_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry.update_user_name
     *
     * @return the value of guu_wiki_entry.update_user_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getUpdateUserName() {
        return updateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry.update_user_name
     *
     * @param updateUserName the value for guu_wiki_entry.update_user_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setUpdateUserName(String updateUserName) {
        this.updateUserName = updateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry.create_time
     *
     * @return the value of guu_wiki_entry.create_time
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry.create_time
     *
     * @param createTime the value for guu_wiki_entry.create_time
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry.update_time
     *
     * @return the value of guu_wiki_entry.update_time
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry.update_time
     *
     * @param updateTime the value for guu_wiki_entry.update_time
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry.browse_amount
     *
     * @return the value of guu_wiki_entry.browse_amount
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public Integer getBrowseAmount() {
        return browseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry.browse_amount
     *
     * @param browseAmount the value for guu_wiki_entry.browse_amount
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setBrowseAmount(Integer browseAmount) {
        this.browseAmount = browseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry.entry_edit_amount
     *
     * @return the value of guu_wiki_entry.entry_edit_amount
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public Integer getEntryEditAmount() {
        return entryEditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry.entry_edit_amount
     *
     * @param entryEditAmount the value for guu_wiki_entry.entry_edit_amount
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setEntryEditAmount(Integer entryEditAmount) {
        this.entryEditAmount = entryEditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry.modify_reason
     *
     * @return the value of guu_wiki_entry.modify_reason
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getModifyReason() {
        return modifyReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry.modify_reason
     *
     * @param modifyReason the value for guu_wiki_entry.modify_reason
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setModifyReason(String modifyReason) {
        this.modifyReason = modifyReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry.entry_status
     *
     * @return the value of guu_wiki_entry.entry_status
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getEntryStatus() {
        return entryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry.entry_status
     *
     * @param entryStatus the value for guu_wiki_entry.entry_status
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setEntryStatus(String entryStatus) {
        this.entryStatus = entryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry.type_id
     *
     * @return the value of guu_wiki_entry.type_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry.type_id
     *
     * @param typeId the value for guu_wiki_entry.type_id
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry.type_name
     *
     * @return the value of guu_wiki_entry.type_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry.type_name
     *
     * @param typeName the value for guu_wiki_entry.type_name
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_wiki_entry.remark
     *
     * @return the value of guu_wiki_entry.remark
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_wiki_entry.remark
     *
     * @param remark the value for guu_wiki_entry.remark
     *
     * @mbggenerated Mon Jun 09 01:27:10 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}